ingressShim:
  defaultIssuerName: letsencrypt-dns01
  defaultIssuerKind: ClusterIssuer
  defaultIssuerGroup: cert-manager.io

extraArgs:
  - --dns01-recursive-nameservers=8.8.8.8:53
  - --dns01-recursive-nameservers-only

serviceAccount:
  name: cert-manager
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::112136120738:role/irsa-certmanager

prometheus:
  enabled: true
  servicemonitor:
    enabled: true
    namespace: monitoring
  # (optional) podmonitor:
  #   enabled: false