name: Build & Push to ECR

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: 112136120738
  ECR_REPO: space-dodger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-ecr-pusher
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Compute image coordinates
        id: meta
        run: |
          echo "IMAGE_URI=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Set up Buildx (cache optional)
        uses: docker/setup-buildx-action@v3

      - name: Build & push (Dockerfile at repo root)
        uses: docker/build-push-action@v6
        with:
          context: .              
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.IMAGE_URI }}:latest
            ${{ steps.meta.outputs.IMAGE_URI }}:${{ steps.meta.outputs.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summary
        run: |
          echo "Image (latest): ${{ steps.meta.outputs.IMAGE_URI }}:latest"
          echo "Image (sha):    ${{ steps.meta.outputs.IMAGE_URI }}:${{ steps.meta.outputs.IMAGE_TAG }}"

      - name: Trivy image scan (report-only)
        uses: aquasecurity/trivy-action@0.27.0
        with:
          scan-type: image
          image-ref: ${{ steps.meta.outputs.IMAGE_URI }}:${{ steps.meta.outputs.IMAGE_TAG }}
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'